spring:
  application:
    name: VectaraxAI
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen3:4b

    google:
      genai:
        api-key: ${GEMINI_API_KEY}

        chat:
          options:
#            model: gemini-2.5-flash
            model: gemini-3.1-flash-lite
            temperature: 0.7
